### ISSUE TITLE
Crash when cycling Prescient Scroll types in inventory

### ISSUE THREAD

**Issue by unilock** [Lyinginbedmon/TricksyFoxes#3]
When cycling through the modes of the Prescient Scroll in the inventory (by sneaking + right-clicking the item), the game will crash upon doing so while the Scroll is set to "Value type: [Yes / No]".

```
[11:03:34] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Container click
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1244) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
	at java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:680) ~[?:?]
	at net.minecraft.class_1703.handler$zmp000$tricksy$cycleNoteType(class_1703.java:921) ~[client-intermediary.jar:?]
	at net.minecraft.class_1703.method_30010(class_1703.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1703.method_7593(class_1703.java:294) ~[client-intermediary.jar:?]
	at net.minecraft.class_481.method_2383(class_481.java:331) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25402(class_465.java:340) ~[client-intermediary.jar:?]
	at net.minecraft.class_481.method_25402(class_481.java:548) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
```

I believe the relevant code is in ScreenHandlerMixin:

https://github.com/Lyinginbedmon/TricksyFoxes/blob/4b9a6144d63832a4cd2ed20817d019831fccc14d/src/main/java/com/lying/tricksy/mixin/ScreenHandlerMixin.java#L61

`TFItems.NOTES.size()` should be `TFItems.NOTES.size() - 1`, no?

**Comment by Lyinginbedmon** [comment]
Good catch! Surprised that one hasn't been reported before. Fortunately booleans aren't used all that often and can be populated with static values.
