### ISSUE TITLE
work table kicks player

### ISSUE THREAD

**Issue by jitterdev** [Lyinginbedmon/TricksyFoxes#5]
using 3.4 on 1.20.1, fabric 0.15.5
```
[01:15:54] [Netty Epoll Server IO #2/ERROR]: Error receiving packet 48
java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3917@24984217' in map Registry[ResourceKey[minecraft:root / minecraft:menu] (Stable)]
        at net.minecraft.class_2540.method_42065(class_2540.java:165) ~[server-intermediary.jar:?]
        at net.minecraft.class_3944.method_11052(class_3944.java:31) ~[server-intermediary.jar:?]
        at net.minecraft.class_2545.method_10838(class_2545.java:45) ~[server-intermediary.jar:?]
        at net.minecraft.class_2545.encode(class_2545.java:14) ~[server-intermediary.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.82.Final.jar:?]
        at net.minecraft.class_2535.method_36942(class_2535.java:220) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10761(class_2535.java:212) ~[server-intermediary.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[01:15:54] [Netty Epoll Server IO #2/ERROR]: Exception occurred in netty pipeline
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3917@24984217' in map Registry[ResourceKey[minecraft:root / minecraft:menu] (Stable)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[netty-codec-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.82.Final.jar:?]
        at net.minecraft.class_2535.method_36942(class_2535.java:220) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10761(class_2535.java:212) ~[server-intermediary.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3917@24984217' in map Registry[ResourceKey[minecraft:root / minecraft:menu] (Stable)]
        at net.minecraft.class_2540.method_42065(class_2540.java:165) ~[server-intermediary.jar:?]
        at net.minecraft.class_3944.method_11052(class_3944.java:31) ~[server-intermediary.jar:?]
        at net.minecraft.class_2545.method_10838(class_2545.java:45) ~[server-intermediary.jar:?]
        at net.minecraft.class_2545.encode(class_2545.java:14) ~[server-intermediary.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.82.Final.jar:?]
        ... 21 more```

**Comment by Lyinginbedmon** [comment]
What were you doing when the crash occurred?

**Comment by jitterdev** [comment]
just opening the work table UI itself causes it, kicking you immediately.

**Comment by Lyinginbedmon** [comment]
Anything in inventory? Any other mods running?

**Comment by jitterdev** [comment]
> Anything in inventory? Any other mods running?

sorry for the delayed response, forgot to send this lol
[mods list.txt](https://github.com/Lyinginbedmon/TricksyFoxes/files/13979705/mods.list.txt)
here's a text file with all my loaded fabric mods on the server. nothing was in my inventory when i tested.

**Comment by Lyinginbedmon** [comment]
That's certainly a lot... Does anything else experience the same problem?

**Comment by jitterdev** [comment]
> That's certainly a lot... Does anything else experience the same problem?

if you mean from the mod, im only aware of the worktable causing this issue.

**Comment by Lyinginbedmon** [comment]
Afraid I can't replicate the issue and with such a vast modlist I'm not sure where to even begin, I'm not even entirely certain that the problem is originating in this mod.
